### ISSUE TITLE
Notice class

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBP-Theme#2]
I need a class that turns an element into a more noticeable box. Something that fits within the theme well but still stands out. Not red because it isn't a warning (although that may also be useful). Maybe blue or yellow or something.

**Comment by d4mation-** [comment]
Is the idea with this just meant as a standard callout (Like "Login Successful" or other such small information alerts) or to accentuate certain objects like a Product?

[It seems like Foundation has some pretty good Callout classes built in.](http://foundation.zurb.com/sites/docs/callout.html)

**Comment by brashrebel** [comment]
Yep, those callouts are basically what I'm looking for. In the immediate future I need to make some text on a form more prominent so something like this is ideal.

**Comment by d4mation-** [comment]
All the Callout classes available in the documentation above are available for use!

**Comment by joelworsham** [comment]
:tada:
